# Generated by Django 5.1.6 on 2025-03-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="userData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userid", models.IntegerField()),
                ("ksm_old", models.IntegerField()),
                ("ksm_new", models.IntegerField()),
                ("tenor_old", models.IntegerField()),
                ("tenor_new", models.IntegerField()),
                ("interest_old", models.IntegerField()),
                ("interest_new", models.IntegerField()),
                ("remaining_debt", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="userLogin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userid", models.IntegerField()),
            ],
        ),
    ]
