# Generated by Django 5.1.6 on 2025-03-24 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userdata",
            name="ksm_new",
        ),
    ]
