# Generated by Django 5.1.6 on 2025-03-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_remove_userdata_ksm_new"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdata",
            name="nama_nasabah",
            field=models.TextField(default=""),
        ),
    ]
