# Generated by Django 5.1.6 on 2025-03-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_userdata_nama_nasabah"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdata",
            name="cicilanperbulan",
            field=models.IntegerField(default=0),
        ),
    ]
